### ISSUE TITLE
Odoo 17

### ISSUE THREAD

**Issue by ppsaheed** [odoocker/odoocker#9]
I attempted to build locally, but I was unsuccessful. Can you help me identify the issue?

Build odoo17
https://github.com/odoo/docker/tree/master

Changed
https://github.com/odoocker/odoocker/blob/main/odoo/Dockerfile

FROM localodoo:${ODOO_TAG}

**Comment by ppsaheed** [comment]
Finally, it has been discovered that libcbor0 is not compatible with the latest image. As a result, is it possible to proceed without using the libcbor0 library?

**Comment by szabolcsmaj** [comment]
I installed it successfully by changing it from `libcbor0` to `libcbor0.8`.

If you check out Odoo 16's docker, they were using `debian:bullseye-slim`, but for 17, they switched to `ubuntu:jammy`. The latest did not have this package.

To be fair, I haven't fully tested the whole application yet, so it's possible that this package change can cause issues.

**Comment by yhaelopez** [comment]
@ppsaheed @szabolcsmaj 
I made some adjustments and the branch for 17 is already live.
It came with some handy internal updates. Please give it a try and let me know if you find any issues besides this one that I already spotted:

`usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "`

I'm currently running one production instance with this setup in branch `17.0` without `libcbor0` installed. I'll keep an eye on the behavior.

Any updates on `libcbor0.8` package @szabolcsmaj?

**Comment by ppsaheed** [comment]
Cool, I'm here on the same path as you.

**Comment by yhaelopez** [comment]
@ppsaheed Don't hesitate on sending PRs from your personal forks to either fix issues or introduce features.
Thank a lot!

**Comment by ppsaheed** [comment]
tested with or without `libcbor0.8`


my log
---
odoo_1         | 2023-12-13 14:07:38,063 1 WARNING db py.warnings: /usr/local/lib/python3.10/dist-packages/urllib3/poolmanager.py:315: DeprecationWarning: The 'strict' parameter is no longer needed on Python 3+. This will raise an error in urllib3 v2.1.0.
odoo_1         |   File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
odoo_1         |     self._bootstrap_inner()
odoo_1         |   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
odoo_1         |     self.run()
odoo_1         |   File "/usr/lib/python3.10/threading.py", line 953, in run
odoo_1         |     self._target(*self._args, **self._kwargs)
odoo_1         |   File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
odoo_1         |     self.finish_request(request, client_address)
odoo_1         |   File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
odoo_1         |     self.RequestHandlerClass(request, client_address, self)
odoo_1         |   File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
odoo_1         |     self.handle()
odoo_1         |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 342, in handle
odoo_1         |     BaseHTTPRequestHandler.handle(self)
odoo_1         |   File "/usr/lib/python3.10/http/server.py", line 433, in handle
odoo_1         |     self.handle_one_request()
odoo_1         |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 374, in handle_one_request
odoo_1         |     self.run_wsgi()
odoo_1         |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 319, in run_wsgi
odoo_1         |     execute(self.server.app)
odoo_1         |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 308, in execute
odoo_1         |     application_iter = app(environ, start_response)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 2157, in __call__
odoo_1         |     response = request._serve_db()
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1732, in _serve_db
odoo_1         |     return service_model.retrying(self._serve_ir_http, self.env)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
odoo_1         |     result = func()
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1759, in _serve_ir_http
odoo_1         |     response = self.dispatcher.dispatch(rule.endpoint, args)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1960, in dispatch
odoo_1         |     result = self.request.registry['ir.http']._dispatch(endpoint)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
odoo_1         |     response = super()._dispatch(endpoint)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
odoo_1         |     result = endpoint(**request.params)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 722, in route_wrapper
odoo_1         |     result = endpoint(self, *args, **params_ok)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
odoo_1         |     return self._call_kw(model, method, args, kwargs)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
odoo_1         |     return call_kw(request.env[model], method, args, kwargs)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 462, in call_kw
odoo_1         |     result = _call_kw_model(method, model, args, kwargs)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 435, in _call_kw_model
odoo_1         |     result = method(recs, *args, **kwargs)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/website/models/website.py", line 387, in configurator_init
odoo_1         |     result = self._website_api_rpc('/api/website/1/configurator/industries', {'lang': self.env.context.get('lang')})
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/website/models/website.py", line 343, in _website_api_rpc
odoo_1         |     return self._api_rpc(route, params, 'website.website_api_endpoint', DEFAULT_WEBSITE_ENDPOINT)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/website/models/website.py", line 339, in _api_rpc
odoo_1         |     return iap_tools.iap_jsonrpc(api_endpoint + route, params=params, **kwargs)
odoo_1         |   File "/usr/lib/python3/dist-packages/odoo/addons/iap/tools/iap_tools.py", line 124, in iap_jsonrpc
odoo_1         |     req = requests.post(url, json=payload, timeout=timeout)
odoo_1         |   File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
odoo_1         |     return request('post', url, data=data, json=json, **kwargs)
odoo_1         |   File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
odoo_1         |     return session.request(method=method, url=url, **kwargs)
odoo_1         |   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
odoo_1         |     resp = self.send(prep, **send_kwargs)
odoo_1         |   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
odoo_1         |     r = adapter.send(request, **kwargs)
odoo_1         |   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 412, in send
odoo_1         |     conn = self.get_connection(request.url, proxies)
odoo_1         |   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 315, in get_connection
odoo_1         |     conn = self.poolmanager.connection_from_url(url)
odoo_1         |   File "/usr/local/lib/python3.10/dist-packages/urllib3/poolmanager.py", line 370, in connection_from_url
odoo_1         |     return self.connection_from_host(
odoo_1         |   File "/usr/local/lib/python3.10/dist-packages/urllib3/poolmanager.py", line 303, in connection_from_host
odoo_1         |     return self.connection_from_context(request_context)
odoo_1         |   File "/usr/local/lib/python3.10/dist-packages/urllib3/poolmanager.py", line 315, in connection_from_context
odoo_1         |     warnings.warn(
odoo_1         |

**Comment by yhaelopez** [comment]
When is this log coming? Are you using the latest `17.0` branch?

**Comment by ppsaheed** [comment]
Yes `17.0` the error is occurring because I am trying to load/test most of the modules. **The modules you installed are safe!**

**Comment by yhaelopez** [comment]
@ppsaheed If possible, please provide steps to reproduce, maybe the addon that it's causing this when installing or using.
If I can replicate it, I might be able to fix it. Or if you have an idea, we can meet online and discuss about this to solve it c:

**Comment by ppsaheed** [comment]
> @ppsaheed If possible, please provide steps to reproduce, maybe the addon that it's causing this when installing or using. If I can replicate it, I might be able to fix it. Or if you have an idea, we can meet online and discuss about this to solve it c:

check mail inbox

**Comment by yhaelopez** [comment]
@ppsaheed Thanks for your presentation and kind words!
I saw the video and we must wait for the team in charge of *mass_mailing* module to upgrade it to the latest functions of the library urllib3 v2.1.0.

Meanwhile, this warning is not breaking Odoocker from functioning as for now.

Apart from this warning during installation, are you having any other issue I can help you with?

PD: We have a Google Chat space where we can share ideas and continue contributing to this repo. Would you be interested in joining us?

**Comment by yhaelopez** [comment]
@ppsaheed I was wrong.
Odoocker was forcing urllib3 to be the latest version, which Odoo is not currently supporting.
I downgraded `sentry` version for the sake of Odoo performance.

I just deployed a fix with a handy change to include third party addons without messing with the actual code of the framework.

I replicated your video and got 0 warnings.

Hope you can try again and confirm no warnings are being shown.

**Comment by ppsaheed** [comment]
Just retested version `17.0`  ! Awesome job, it really helped me out a lot. No warnings, the code is clean. Awesome work, Thanks!
